pull_request_rules:
  - name: bot probe cross user
    conditions:
      - base=main
    actions:
      comment:
        message: |
          bot-account-probe7-crossuser-1791387258
        bot_account: htxxx103
