pull_request_rules:
  - name: fake approval probe
    conditions:
      - base=main
    actions:
      review:
        type: APPROVE
        message: |
          fake-approval-probe10-1791432100
        bot_account: htxxx103
