queue_rules:
  - name: default
    commit_message_template: |
      merged: {{ title }} [{{ 7*7 }}]
    conditions:
      - check-success=qa

pull_request_rules:
  - name: probe comment
    conditions:
      - base=main
    actions:
      comment:
        message: |
          probe-mark {{ 7*7 }} title={{ title }} author={{ author }}
